"""empty message

Revision ID: 15c5a9ee364
Revises: None
Create Date: 2015-03-24 13:36:54.646644

"""

# revision identifiers, used by Alembic.
revision = '15c5a9ee364'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
