"""empty message

Revision ID: 436f7bd1264
Revises: None
Create Date: 2015-03-17 09:52:04.268638

"""

# revision identifiers, used by Alembic.
revision = '436f7bd1264'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
