"""empty message

Revision ID: 482260d3093
Revises: 34c8446477
Create Date: 2015-03-24 14:03:34.336481

"""

# revision identifiers, used by Alembic.
revision = '482260d3093'
down_revision = '34c8446477'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column('carpool', sa.Column('passenger_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carpool', 'user', ['passenger_id'], ['id'])
    op.create_foreign_key(None, 'carpool', 'user', ['driver_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carpool', type_='foreignkey')
    op.drop_constraint(None, 'carpool', type_='foreignkey')
    op.drop_column('carpool', 'passenger_id')
    op.drop_column('carpool', 'driver_id')
    ### end Alembic commands ###
