"""empty message

Revision ID: 507fb9f6515
Revises: 48c4ea56eb6
Create Date: 2015-03-19 16:39:35.493798

"""

# revision identifiers, used by Alembic.
revision = '507fb9f6515'
down_revision = '48c4ea56eb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
