"""empty message

Revision ID: e78f02d3e6
Revises: None
Create Date: 2015-03-17 10:00:37.419683

"""

# revision identifiers, used by Alembic.
revision = 'e78f02d3e6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
